// APP INIT ACTIONS
export const APP_INITIALIZED = 'APP_INITIALIZED';
export const LOAD_ACCOUNTS = 'LOAD_ACCCOUNTS';
export const LOAD_WALLETS = 'LOAD_WALLETS';
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const PAGE_LOADING = 'PAGE_LOADING';

//AUTH ACTIONS
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';

// ACCOUNTS ACTIONS
export const ACCOUNT_SELECTED = 'ACCOUNT_SELECTED';
export const LOAD_ACCOUNTS_SUMMARY = 'LOAD_ACCOUNTS_SUMMARY';
export const LOAD_ACCOUNTS_AVAILABLE_YEARS = 'LOAD_ACCOUNTS_AVAILABLE_YEARS';
export const ACCOUNT_ADDED = 'ACCOUNT_ADDED';
export const YEAR_SELECTED = 'YEAR_SELECTED';

// WALLET ACTIONS
export const WALLETS_LOADED = 'WALLETS_LOADED';
export const WALLET_SELECTED = 'WALLET_SELECTED';
export const ADD_WALLET = 'ADD_WALLET';

// TRANSACTION ACTIONS
export const LOAD_INCOMING_TRANSACTIONS = 'LOAD_INCOMING_TRANSACTIONS';
export const TRANSACTION_SELECTED = 'TRANSACTION_SELECTED';
export const TRANSACTION_FORCE_UNSELECT = 'TRANSACTION_FORCE_UNSELECT';
export const SELECT_ALL_TRANSACTIONS = 'SELECT_ALL_TRANSACTIONS';
export const INSPECT_TRANSACTION = 'INSPECT_TRANSACTION';
export const TRANSACTION_ACCEPTED = 'TRANSACTION_ACCEPTED';
export const BULK_ACCEPT_TRANSACTIONS = 'BULK_ACCEPT_TRANSACTIONS';
export const BULK_DISCARD_TRANSACTIONS = 'BULK_DISCARD_TRANSACTIONS';
export const TRANSACTION_DISCARDED = 'TRANSACTION_DISCARDED';

// TRANSACTION-FILTER ACTIONS
export const FILTERABLE_COINS_RECEIVED = 'FILTERABLE_COINS_RECEIVED';

// RECORDS ACTIONS
export const LOAD_RECORD_TYPES = 'LOAD_RECORD_TYPES';
export const LOAD_RECORDS = 'LOAD_RECORDS';
export const LOAD_FEE_RECORDS = 'LOAD_FEE_RECORDS';

//APP ACTIONS
export const SIDEBAR_TOGGLED = 'SIDEBAR_TOGGLED';

// MODAL
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
